// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxMfp0tZ3pUf2OB6SRsqOAmna4WdmqY0',
    appId: '1:762641320270:web:82d759ad2e3c43064b361f',
    messagingSenderId: '762641320270',
    projectId: 'uap-login',
    authDomain: 'uap-login.firebaseapp.com',
    storageBucket: 'uap-login.firebasestorage.app',
    measurementId: 'G-0F0HG6JMZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLSykhWfeRIQM1V30SEm-OOZanDQ6Y0RE',
    appId: '1:762641320270:android:cceea21f727b1a094b361f',
    messagingSenderId: '762641320270',
    projectId: 'uap-login',
    storageBucket: 'uap-login.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsxMfp0tZ3pUf2OB6SRsqOAmna4WdmqY0',
    appId: '1:762641320270:web:885b993498d3647d4b361f',
    messagingSenderId: '762641320270',
    projectId: 'uap-login',
    authDomain: 'uap-login.firebaseapp.com',
    storageBucket: 'uap-login.firebasestorage.app',
    measurementId: 'G-JQV8HR3KG4',
  );
}
